on:
  push:
    branches:    
      - 'master'

name: 'Build: GNU + Linux (ARM64)'

jobs:
  linux_aarch64:
    name: GNU + Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libssl-dev build-essential > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build depi
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu
      - name: Prepare depi for upload
        run: |
          cd ./target/aarch64-unknown-linux-gnu/release/
          strip -v --strip-all ./libdepi.a
          chmod +x ./depi
          tar -cvf aarch64-depi.gnu+linux.tar \
          depi \
          libdepi.so \
          libdepi.a
      - name: Upload depi build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-depi.gnu+linux
          path: ./target/aarch64-unknown-linux-gnu/release/aarch64-depi.gnu+linux.tar
          if-no-files-found: error
