on:
  release:
    types: [published]

name: 'Publish: crates.io'

jobs:
  publish:
    name: 'Publish: crates.io'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch dependencies
        run:  |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libsixel-dev libsixel-bin libssl-dev build-essential > /dev/null
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args:  ${{ secrets.NEW_CRATES_LOGIN }}
      - name: Package depi
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: Publish depi
        uses: actions-rs/cargo@v1
        with:
          command: publish