on:
  push:
    branches:    
      - 'master'

name: 'Package: RPM for GNU + Linux (x86_64)'

jobs:
  rpm_x86-64:
    name: Fedora GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged
    steps:
      - name: Install requisite packages
        run: |
          sudo dnf -q -y update > /dev/null
          sudo dnf -q -y install git gh gcc rpm-build rpmdevtools rpmlint python3-rust2rpm rust-packaging rust cargo tree openssl openssl-devel perl perl-FindBin perl-lib > /dev/null
      - name: Checkout codebase
        run: |
          printf "${{ secrets.PAT }}" | gh auth login --with-token
          gh repo clone Dirout/depi
          cd ./depi
          printf "Repository:\n" && tree -a ./
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Generate RPM package specification
        run: |
          cd ./depi
          rust2rpm .
          rpmlint ./rust-depi.spec
          printf "Repository:\n" && tree -a ./
      - name: Commit changes to RPM package specification file, if any
        run: |
          cd ./depi
          git config --global --add safe.directory ./
          git config --global user.name 'depi'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git add ./rust-depi.spec
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatically updated RPM package specification"
          git push https://${{ secrets.PAT }}@github.com/Dirout/depi.git
      - name: Build & package depi
        run: |
          cd ./depi
          cargo install cargo-generate-rpm
          cargo build --release --all-features
          cargo generate-rpm
          tree -a ./
      - name: Upload depi package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-depi.rpm.gnu+linux
          path: "./depi/target/generate-rpm/*.rpm"
          if-no-files-found: error