on:
  push:
    branches:    
      - 'master'

name: 'Build: Windows (x86_64)'

jobs:
  windows_x86-64:
    name: Windows (x86_64)
    runs-on: windows-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-gnu
          target: x86_64-pc-windows-gnu
          default: true
          profile: minimal
      - name: Build depi
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - name: Prepare depi for upload
        run: |
          cd ./target/x86_64-pc-windows-gnu/release/
          tar -czvf x86_64-depi.win32.zip `
          depi.exe `
          depi.dll `
          libdepi.a `
          libdepi.dll.a
      - name: Upload depi build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-depi.win32
          path: ./target/x86_64-pc-windows-gnu/release/x86_64-depi.win32.zip
          if-no-files-found: error