on:
  push:
    branches:    
      - 'master'

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libssl-dev build-essential > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build depi
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Prepare depi for upload
        run: |
          cd ./target/x86_64-unknown-linux-gnu/release/
          strip -v --strip-all ./depi
          strip -v --strip-all ./libdepi.so
          strip -v --strip-all ./libdepi.a
          chmod +x ./depi
          tar -cvf x86_64-depi.gnu+linux.tar \
          depi \
          libdepi.so \
          libdepi.a
      - name: Upload depi build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-depi.gnu+linux
          path: ./target/x86_64-unknown-linux-gnu/release/x86_64-depi.gnu+linux.tar
          if-no-files-found: error